package org.cvcm.utils;

public interface Constants {
    String TOMCAT_SERVER_FILE_NAME = "TOMCAT_SERVER_FILE_NAME";
    String TOMCAT_SERVER_FILE_BACKUP_NAME = "TOMCAT_SERVER_FILE_BACKUP_NAME";
    String LOGGER_FILE = "LOGGER_FILE";
    String TOMCAT_INSTALLATION_DIRS_JSON = "TOMCAT_INSTALLATION_DIRS_JSON";

    String TOMCAT_CONFIG_DIR ="TOMCAT_CONFIG_DIR";

    String APP_NAME ="APP_NAME";

    String TOMCAT_DIR_PREFIXES = "TOMCAT_DIR_PREFIXES";
}
